openapi: '3.0.2'
info:
  title: General Testo API
  version: '1.0'
servers:
  - url: https://{location}
paths:
  /o:
    get:
      summary: Returns the result of the last measurement
      tags:
        - t300
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: object
        default:
          description: Unexpected error
    post:
      summary: Starts a measurement
      tags:
        - t300
      requestBody:
        description: XML content to select the measurements
        required: true
        content:
          application/xml:
            schema:
              type: object
      responses:
        '200':
          description: OK
        default:
          description: Unexpected error
  /data:
    get:
      summary: Returns the TJF object of the current measurement
      tags:
        - t300
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
        default:
          description: Unexpected error
  /deviceInfo:
    get:
      summary: Returns a JSON object with the device information
      tags:
        - t300
        - t400
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../schema/v2.0.0/deviceInfo-schema-legacy.json'
        default:
          description: Unexpected error
  /contact:
    get:
      summary: Returns a JSON object with the contacts
      tags:
        - t400
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../schema/v2.0.0/contact-schema-v2.0.0.json'
        default:
          description: Unexpected error
    post:
      summary: Adds a Contact object
      tags:
        - t400
      requestBody:
        description: Object of the Contact object
        required: true
        content:
          application/json:
            schema:
              $ref: '../schema/v2.0.0/contact-schema-v2.0.0.json'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /contact/{uuid}:
    get:
      summary: Returns a JSON object of the contact by UUID
      tags:
        - t400
      parameters:
        - name: uuid
          in: path
          description: UUID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../schema/v2.0.0/contact-schema-v2.0.0.json'