openapi: '3.0.2'
info:
  title: General Testo API
  version: '1.0'
servers:
  - url: https://{location}
paths:
  /deviceInfo:
    get:
      summary: Returns a JSON object with the device information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../schema/v2.0.0/deviceInfo-schema-legacy.json'
        default:
          description: Unexpected error
  /contact:
    get:
      summary: Returns a JSON object with the contacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../schema/v2.0.0/contact-schema-v2.0.0.json'
        default:
          description: Unexpected error
  /measuringPoints:
    get:
      summary: Returns a JSON object with the measuring points
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../schema/v2.0.0/measuringpoint-schema-v2.0.0.json'
        default:
          description: Unexpected error
