openapi: '3.0.2'
info:
  title: General Testo API
  version: '1.0'
servers:
  - url: https://{location}
paths:
  /deviceInfo:
    get:
      summary: Returns a JSON object with the device information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../schema/v2.0.0/deviceInfo-schema-legacy.json'
        default:
          description: Unexpected error
  /contact:
    get:
      summary: Returns a JSON object with the contacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../schema/v2.0.0/contact-schema-v2.0.0.json'
        default:
          description: Unexpected error
    post:
      summary: Adds a Contact object
      requestBody:
        description: Object of the Contact object
        required: true
        content:
          application/json:
            schema:
              $ref: '../schema/v2.0.0/contact-schema-v2.0.0.json'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
  /contact/{uuid}:
    get:
      summary: Returns a JSON object of the contact by UUID
      parameters:
        - name: uuid
          in: path
          description: UUID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../schema/v2.0.0/contact-schema-v2.0.0.json'